#!/usr/local/bin/python3

import subprocess
import json
import base64
import sys

def read_command(command):
    result = subprocess.run(command.split(), stdout=subprocess.PIPE)
    return result.stdout.decode('utf-8')


def list_secrets():
    text = read_command("kubectl get secrets")
    items = map(lambda it: it.split(), text.splitlines())
    filtered = filter(lambda it: len(it) == 4 and it[0] != "NAME", items)
    secrets = list(map(lambda it: it[0], filtered))

    return secrets


def read_secret(secret):
    text = read_command("kubectl get secret " + secret + " -o json")
    data = json.loads(text)['data']
    items = list(map(lambda kv: (kv[0], base64.b64decode(kv[1]).decode('utf-8')), data.items()))
    return items


def split_secrets():
    items = map(lambda it: it.split(), test.splitlines())
    filtered = filter(lambda it: len(it) == 4 and it[0] != "NAME", items)
    secrets = list(map(lambda it: it[0], filtered))

    return secrets

def main(argv):
    if len(argv) == 1:
        secrets = list_secrets()
        for s in secrets:
            print(s)
    elif len(argv) == 2:
        secrets = read_secret(argv[1])
        for s in secrets:
            print(s[0] + "\t" + s[1])
    else:
        println("Expected zero or one arguments")

if __name__ == "__main__":
    main(sys.argv)
